services:
  firebase:
    image: andreysenov/firebase-tools
    command: firebase emulators:start --project demo-project
    ports:
      - "4000:4000"  # UI
      - "8080:8080"  # Firestore
    volumes:
      - ./firebase.json:/home/node/firebase.json
    working_dir: /home/node